name: Tests and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build
  publish:
    runs-on: ubuntu-latest
    needs: build
    # if: contains(github.ref, 'main')
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish GitHub
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{secrets.GITHUB_TOKEN}}
    - name: Publish Nuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
      